services:
 
   # Application Service
  app:
    container_name: mangavel-app
    build:
      context: .
      dockerfile: ./php-docker/Dockerfile-php
    networks:
      - rede_mango
    volumes:
      - .:/app
    ports:
      - "5173:5173"
      - "8000:8000"
    working_dir: /app
    depends_on:
      - db
  #database
  db:
    image: mongo
    container_name: mongodb
    networks:
      - rede_mango
    volumes: 
      - /mangavel:/data/db
    ports: 
      - "27017:27017"

networks: 
  rede_mango:
  
volumes: 
  mangavel: