services:
 
   # Application Service
  app:
    container_name: mangavel-app
    build:
      context: .
    networks:
      - rede_mango
    ports:
      - "5173:5173"
      - "8000:8000"
  #databasez
  db:
    image: mongo
    container_name: mongodb
    networks:
      - rede_mango
    volumes: 
      - mangavel:/data/db
    ports: 
      - "27017:27017"

networks: 
  rede_mango:
  
volumes: 
  mangavel: