FROM php:latest

# Instalar unzip
RUN apt update && apt install -y unzip

# Instalar a extensão mongod
RUN pecl install mongodb && docker-php-ext-enable mongodb

# Instalar a extensão pcntl
RUN docker-php-ext-install pcntl

# Instalar Composer de outra forma, mas com o mesmo resultado
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Configurar as variáveis de ambiente
ENV HOME="/root"
ENV PATH="/root/.composer/vendor/bin:${PATH}:/root/.bun/bin"

# Instalar Bun
RUN curl -fsSL https://bun.sh/install | bash

# Criar alguns symlinks para o executável bun
RUN ln -s $(which bun) /usr/local/bin/npm
RUN ln -s $(which bunx) /usr/local/bin/npx

# Exponha a porta 8000 para o PHP
EXPOSE 8000

#Exponhe a porta do VITE < front
EXPOSE 5173

# Defina o diretório de trabalho no container
WORKDIR /app

# Copie os arquivos da aplicação Laravel para o container
COPY . .

#daí o note de ian é mt ruim tem que rodar isso aqui:
RUN composer config --global process-timeout 30000

# Instale as dependências do Laravel via Composer
RUN composer install --no-dev --optimize-autoloader



#gerando a chave 
RUN php artisan key:generate

#migrations
RUN php artisan migrate 

# Padrãozinho para rodar
CMD ["composer" , "run" , "dev"]